### ISSUE TITLE
V1.0.0 refactor

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irishub#2086]
## Summary

An epic to track all v1.0.0 refactor related issues and PRs.

### DONE

- [x] [Overwrite mint module](https://github.com/irisnet/irishub/issues/2089)
- [x] [Refactor guardian module](https://github.com/irisnet/irishub/issues/2090)
- [x] [Refactor HTLC module](https://github.com/irisnet/irishub/issues/2095)
- [x] [Refactor coinswap module](https://github.com/irisnet/irishub/issues/2094)
- [x] [Refactor random module](https://github.com/irisnet/irishub/issues/2092)
- [x] [Migrate iriscli test](https://github.com/irisnet/irishub/issues/2098)
- [x] [Add REST test](https://github.com/irisnet/irishub/issues/2099)
- [x] [Support NFT](https://github.com/irisnet/irishub/issues/2126)
- [x] bump to latest cosmos-sdk(https://github.com/irisnet/irishub/pull/2381)
- [x] [Refactor asset module](https://github.com/irisnet/irishub/issues/2091)
- [x] [Refactor service module](https://github.com/irisnet/irishub/issues/2093)
- [x] [Redirect REST APIs URI](https://github.com/irisnet/irishub/issues/2096)
- [x] [Script to migrate application state](https://github.com/irisnet/irishub/issues/2097)
- [x] [Coin adapter](https://github.com/irisnet/irishub/issues/2087)
- [x] [Initialize system variables](https://github.com/irisnet/irishub/issues/2088) 
- [x] [Update document](https://github.com/irisnet/irishub/issues/2100)
