### ISSUE TITLE
Prepare to release v0.17.0-rc0

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irishub#2256]
### Summary

Prepare to release v0.17.0-rc0

### WIP

- [ ] Add changelog

### DONE

- [x] Revert service `IntraTxCounter` to be stored in db instead of ctx, #2259 
- [x] [Refactor rand module](#2249)
- [x] [Simplify and improve FungibleToken model and related code](#2239)
- [x] Add more tags in service (include the tx signer at least), #2257 
- [x] Track coin flow  in service `EndBlocker` (deduct service fee, slash & refund), #2257 
- [x] [Make bytes output format consistent](#2255)
- [x]  enhance service, #2260 , #2262 
- [x] Add service context state change callback, #2308 
- [x] [test] params change & genesis export 
- [x] Check docs
- [x] Modify service timeout logic, #2294
